services:
  - type: web
    name: uptask-backend
    env: node
    branch: main
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm run build && pnpm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false 
      - key: JWT_SECRET
        sync: false 